# Generated by Django 2.2.9 on 2020-09-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_auto_20200916_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='User',
            new_name='user',
        ),
    ]
